name: Code Review

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm i

    - name: Run ESLint for code review
      run: npx eslint . --ext .js,.jsx,.ts,.tsx | tee eslint-results.txt
    
    - name: Echo ESLint results
      run: cat eslint-results.txt
