name: Dependency Updates

on:
    schedule:
        - cron: '0 0 * * 6'  # Runs every Saturday at midnight

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v2
          with:
            node-version: '14'

        - run: npm i 
        - run: npm update